apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k4oh4xnz6-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k4oh4xnz6-go 
  name: k4oh4xnz6-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k4oh4xnz6-go 
